language: php

php:
  - 7.1

before_script:
  - cp .env.example .env
  - php artisan key:generate
  - mysql -e 'create database websports;'
  - composer self-update
  - composer install --no-interaction

script:
- vendor/bin/phpunit
